<?php
/**
 * @file
 * Custom module for the Backdrop API site.
 */

/**
 * Implements hook_block_info().
 */
function backdropapi_block_info() {
  $blocks['form_api_matrix'] = array(
    'info' => t('Form API Matrix'),
    'description' => t('Displays all Form API elements and properties in a matrix table.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function backdropapi_block_view($delta = '', $settings = array(), $contexts = array()) {
  $block = array();

  if ($delta == 'form_api_matrix') {
    $block['subject'] = '';
    $block['content'] = backdropapi_form_api_matrix();
  }

  return $block;
}

/**
 * Returns a matrix table of Form API elements and properties.
 */
function backdropapi_form_api_matrix() {
  $variables = array();

  // Get lists of Form API elements & properties.
  $elements = views_get_view_result('form_api', 'attachment_1');
  $properties = views_get_view_result('form_api', 'attachment_2');

  // Setup the table header.
  $variables['header'][] = '<a href="#type">' . t('type') . '</a>';
  foreach ($elements as $element) {
    $variables['header'][] = '<a href="#' . $element->node_title . '">' . $element->node_title . '</a>';
  }

  // Setup the table rows.
  foreach ($properties as $property) {
    $row = array('<a href="#' . $property->node_title . '">#' . $property->node_title . '</a>');

    foreach ($elements as $element) {
      // Get all properties for this element.
      $element_properties = array();
      foreach ($element->field_field_properties_field_property as $element_property) {
        $element_properties[] = $element_property['rendered']['#markup'];
      }

      // Set the value of the cell.
      if (in_array($property->node_title, $element_properties)) {
        $value = 'x';
      }
      else {
        $value = '-';
      }
      $row[] = $value;
    }

    $variables['rows'][] = $row;
  }

  return theme('table', $variables);
}
